FROM python:3.11-slim

WORKDIR /app

# copiar requirements
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copiar TODO el backend
COPY . /app/backend

# MUY IMPORTANTE: agregar al path
ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]